/// <reference types="cypress" />
/// <reference types="cypress-axe" />

import type { Result } from 'axe-core';
import routes from '../fixtures/routes.json';
import { COMPREHENSIVE_AAA_OPTIONS } from '../support/axe-rules';

/**
 * WCAG AAA Comprehensive Accessibility Compliance Tests
 *
 * This test suite uses axe-core to automatically check for WCAG AAA violations across all routes.
 *
 * @see https://www.w3.org/WAI/WCAG22/quickref/?versions=2.2&levels=aaa
 *
 * Coverage includes:
 * - Color contrast (Enhanced): 7:1 for normal text, 4.5:1 for large text (1.4.6 AAA)
 * - ARIA attributes and roles (4.1.2, 4.1.3)
 * - Form labels and instructions (3.3.2)
 * - Heading structure and hierarchy (1.3.1, 2.4.10 AAA)
 * - Keyboard accessibility (2.1.1, 2.1.2)
 * - Link purpose and descriptiveness (2.4.4, 2.4.9 AAA)
 * - Image text alternatives (1.1.1)
 * - Language identification (3.1.1, 3.1.2)
 * - Landmarks and page structure (1.3.1, 2.4.1)
 *
 * Note: Some AAA criteria cannot be automatically tested and require manual verification.
 * See docs/accessibility/manual-testing-guide.md for manual test procedures.
 */

describe('WCAG AAA Accessibility Compliance', () => {
  // Filter and prepare routes
  const testableRoutes = (routes as string[]).filter(
    (route: string) => !route.endsWith('/new') && !route.endsWith('/crear')
  );

  const MOCK_OBJECT_ID = '5f9d88b9c2a0a20017a4b0a1'; // Valid 24-char hex ObjectId

  // Generate a test case for each route
  testableRoutes.forEach((route: string) => {
    // Replace '/id' segment (generated by discover-routes.js) with a mock ID
    const effectiveRoute = route.replace(/\/id($|\/)/, `/${MOCK_OBJECT_ID}$1`);

    describe(`Accessibility checks for ${effectiveRoute}`, () => {
      beforeEach(() => {
        // Ignore uncaught exceptions (like hydration errors or next.js profiling issues)
        cy.on('uncaught:exception', () => {
          return false;
        });

        cy.visit(`${effectiveRoute}?audit=true`);
        cy.wait(2000); // Wait for dynamic content
        cy.injectAxe();
      });

      it('should pass comprehensive axe-core WCAG AAA checks', () => {
        // Run WCAG AAA checks with comprehensive rule set
        cy.checkA11y(
          undefined,
          COMPREHENSIVE_AAA_OPTIONS,
          (violations: Result[]) => {
            if (violations.length) {
              const formattedViolations = violations.map((v: Result) => ({
                route: effectiveRoute,
                rule: v.id,
                impact: v.impact,
                description: v.description,
                nodes: v.nodes.length,
                helpUrl: v.helpUrl,
                wcagTags: v.tags.filter((tag) => tag.startsWith('wcag')),
                elements: v.nodes
                  .map((n: Result['nodes'][0]) => n.target.join(' > '))
                  .join(', '),
              }));

              const errorMessage =
                `\n\nWCAG AAA VIOLATIONS ON ${effectiveRoute}:\n\n` +
                formattedViolations
                  .map(
                    (v: (typeof formattedViolations)[0]) =>
                      `[${v.impact?.toUpperCase()}] ${v.rule}\n` +
                      `  WCAG: ${v.wcagTags.join(', ')}\n` +
                      `  Description: ${v.description}\n` +
                      `  Affected elements (${v.nodes}): ${v.elements}\n` +
                      `  Help: ${v.helpUrl}\n`
                  )
                  .join('\n');

              cy.log(errorMessage);
              throw new Error(errorMessage);
            } else {
              cy.log(
                `✓ ${effectiveRoute} passed comprehensive WCAG AAA compliance`
              );
            }
          }
        );
      });

      it('should have descriptive link text (2.4.9 AAA)', () => {
        // Check for vague link text
        const vagueTerms = ['click here', 'read more', 'here', 'link'];

        cy.get('body').then(($body) => {
          const $links = $body.find('a:visible');

          if ($links.length === 0) {
            // No links found, test passes
            cy.log('No visible links found on this page');
            return;
          }

          $links.each((_, link) => {
            const $link = Cypress.$(link);
            const linkText = $link.text().trim().toLowerCase();
            const ariaLabel = $link.attr('aria-label')?.toLowerCase() || '';
            const title = $link.attr('title')?.toLowerCase() || '';
            const combinedText = `${linkText} ${ariaLabel} ${title}`.trim();

            // Link text should be descriptive, not generic
            // Only flag if it's EXACTLY a vague term or very short
            const isVague = vagueTerms.some((term) => combinedText === term);

            if (isVague) {
              // Check if link has descriptive context from aria-label or title
              if (!ariaLabel && !title) {
                cy.log(`Warning: Link with vague text: "${linkText}"`);
              }
            }
          });
        });
      });

      it('should have section headings for content organization (2.4.10 AAA)', () => {
        // Main content should have headings to organize sections
        cy.get('main, [role="main"], article').then(($main) => {
          if ($main.length > 0) {
            const headings = $main.find('h1, h2, h3, h4, h5, h6');
            const paragraphs = $main.find('p');

            // If there's substantial content, it should have section headings
            if (paragraphs.length > 3 && headings.length === 0) {
              cy.log(`Info: Main content could benefit from section headings`);
            }
          }
        });
      });

      it('should not use images of text (1.4.9 AAA)', () => {
        // Check for images that might contain text
        cy.get('body').then(($body) => {
          const $images = $body.find('img:visible');

          if ($images.length === 0) {
            // No images found, test passes
            cy.log('No images found on this page');
            return;
          }

          $images.each((_, img) => {
            const alt = Cypress.$(img).attr('alt') || '';

            // Heuristic: if alt text is very long, image might contain significant text
            const wordCount = alt.split(' ').filter((w) => w.length > 0).length;
            expect(
              wordCount,
              `Image alt text should be concise (max 10 words). Found ${wordCount} words in: "${alt.substring(0, 100)}..."`
            ).to.be.lessThanOrEqual(10);
          });
        });
      });

      it('should have enhanced color contrast for all text (1.4.6 AAA)', () => {
        // This is checked by axe-core with the color-contrast-enhanced rule
        // But we can do additional spot checks
        cy.get('p, h1, h2, h3, h4, h5, h6, li, td, button, a').each(($el) => {
          const styles = window.getComputedStyle($el[0]);
          const bgColor = styles.backgroundColor;

          // Log elements with transparent backgrounds (harder to verify)
          if (bgColor === 'rgba(0, 0, 0, 0)' || bgColor === 'transparent') {
            // Element inherits background, axe-core will check this
          }
        });
      });

      it('should identify page language (3.1.1)', () => {
        cy.get('html').should('have.attr', 'lang');
        cy.get('html')
          .invoke('attr', 'lang')
          .should('match', /^[a-z]{2}(-[A-Z]{2})?$/);
      });

      it('should have a main landmark', () => {
        cy.get('main, [role="main"]').should('have.length.at.least', 1);
      });
    });
  });
});
