/// <reference types="cypress" />
/// <reference types="cypress-axe" />

import type { Result } from 'axe-core';
// Import routes statically since discover-routes runs before Cypress
import routes from '../fixtures/routes.json';

describe('WCAG AAA Accessibility Compliance', () => {
  // Filter and prepare routes
  const testableRoutes = (routes as string[]).filter(
    (route: string) => !route.endsWith('/new') && !route.endsWith('/crear')
  );

  const MOCK_OBJECT_ID = '5f9d88b9c2a0a20017a4b0a1'; // Valid 24-char hex ObjectId

  // Generate a test case for each route
  testableRoutes.forEach((route: string) => {
    // Replace '/id' segment (generated by discover-routes.js) with a mock ID
    const effectiveRoute = route.replace(/\/id($|\/)/, `/${MOCK_OBJECT_ID}$1`);

    it(`should verify accessibility for ${effectiveRoute}`, () => {
      // Ignore uncaught exceptions (like hydration errors or next.js profiling issues)
      cy.on('uncaught:exception', () => {
        return false;
      });

      cy.visit(`${effectiveRoute}?audit=true`);
      cy.wait(2000); // Wait for dynamic content
      cy.injectAxe();

      // Run WCAG AAA checks
      cy.checkA11y(
        undefined,
        {
          runOnly: {
            type: 'tag',
            values: ['wcag2aaa', 'wcag21aaa', 'wcag22aaa', 'best-practice'],
          },
        },
        (violations: Result[]) => {
          if (violations.length) {
            const formattedViolations = violations.map((v: Result) => ({
              route: effectiveRoute,
              rule: v.id,
              impact: v.impact,
              description: v.description,
              nodes: v.nodes.length,
              helpUrl: v.helpUrl,
              elements: v.nodes
                .map((n: Result['nodes'][0]) => n.target.join(' > '))
                .join(', '),
            }));

            const errorMessage =
              `\n\nWCAG AAA VIOLATIONS ON ${effectiveRoute}:\n\n` +
              formattedViolations
                .map(
                  (v: (typeof formattedViolations)[0]) =>
                    `[${v.impact?.toUpperCase()}] ${v.rule}\n` +
                    `  Description: ${v.description}\n` +
                    `  Affected elements (${v.nodes}): ${v.elements}\n` +
                    `  Help: ${v.helpUrl}\n`
                )
                .join('\n');

            cy.log(errorMessage);
            throw new Error(errorMessage);
          } else {
            cy.log(`${effectiveRoute} passed WCAG AAA compliance`);
          }
        }
      );
    });
  });
});
